export const SCENE_KEYS = Object.freeze({
  TITLE_SCENE: 'TITLE_SCENE',  
  PRELOAD_SCENE: 'PRELOAD_SCENE',
    CAMPUS_SCENE: 'CAMPUS_SCENE',
    DORM_SCENE: 'DORM_SCENE',
    TEST_SCENE: 'TEST_SCENE',
    UI_SCENE: 'UI_SCENE',
  });